version: '3.9'
services:
    database:
        image: mongo
        networks:
            - backend
    
    server:
        build: ./server
        depends_on:
            - database
        ports:
            - "8080:3000"
        networks:
            - backend
            - global

    client:
        build: ./client
        networks:
            - global

    proxy:
        image: nginx
        networks:
            - global

networks:
    global:
        name: global
    backend:
        name: backend