version: '3.9'
services:
    database:
        image: mongo:6.0.3
        networks:
            - backend
        ports:
            - "27017"
        volumes:
            - "./data:/data/db"

    server:
        build: ./server
        depends_on:
            - database
        ports:
            - "8080:3000"
        networks:
            - backend
            - global

    client:
        build: ./client
        networks:
            - global

    proxy:
        build: ./proxy
        networks:
            - global
        ports:
            - "80:80"
        depends_on:
            - client
            - server
        restart: always

networks:
    global:
        name: global
    backend:
        name: backend
