version: '3.9'
services:
    database:
        image: mongo
        networks:
            - backend
    
    server:
        build: ./server/Dockerfile
        depends_on:
            - database
        ports:
            - "8080:3000"
        networks:
            - backend
            - global

    client:
        build: ./client/Dockerfile
        networks:
            - global

    proxy:
        image: nginx
        networks:
            - global

networks:
    global:
        driver: global-driver
    backend:
        driver: backend-driver