version: '3.9'
services:
    database:
        image: mysql
    
    server:
        build: ./server/Dockerfile
        depends_on:
            - database
        ports:
            - "8080:3000"
    
    client:
        build: ./client/Dockerfile

    proxy:
        image: nginx